[package]
name = "hermes"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
imap = "2.4.1"

lettre = { version = "0.11", features = ["smtp-transport", "builder"] }
native-tls = "0.2"

